name: bookly_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  auto_route: ^9.3.0+1
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  easy_localization: ^3.0.7
  easy_logger: ^0.0.2
  dio: ^5.5.0+1
  form_builder_validators: ^11.0.0
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  sentry_dio: ^8.9.0
  sentry_flutter: ^8.13.0
  device_preview: ^1.1.0
  fluttertoast: ^8.2.10
  device_info_plus: ^11.1.1
  pinput: ^5.0.0
  skeletonizer: ^1.4.2
  lottie: ^3.1.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  auto_route_generator: ^9.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_gen:
  output: lib/generated



